#!/bin/bash

# Establishing home directories, these will change obviously depending on your machine
piDir="/home/pi/RetroPie/roms"
homeDir="/home/toadkarter/Documents/pitransfer"

for dir in "$homeDir"/*
do
  if [ -d "$dir" ];then

    scp "$homeDir"/$(basename "$dir")/* pi@192.168.0.242:"$piDir"/$(basename "$dir")

  fi
done